spring:
  security:
    user:
      name: admin
      password: secret123

  datasource:
    url: jdbc:postgresql://localhost:15432/usj_db
    username: usj_user
    password: secretpass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create  # 開発環境ではcreateを使用（テーブルを毎回再作成）
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true  # JPAのテーブル作成後にdata.sqlを実行

  sql:
    init:
      mode: always  # アプリ起動時にdata.sqlを実行

# （任意）Actuator のエンドポイント制御
management:
  endpoints:
    web:
      exposure:
        include: health,info

# Springdoc OpenAPI の設定
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs 